language: go

sudo: required

services:
    - docker

before_install:
    # libseccomp in trusty is not new enough, need backports version.
    - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' > /etc/apt/sources.list.d/backports.list"
    - sudo apt-get update

install:
    - sudo apt-get install btrfs-tools
    - sudo apt-get install libseccomp2/trusty-backports
    - sudo apt-get install libseccomp-dev/trusty-backports
    - docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter

before_script:
    - export PATH=$HOME/gopath/bin:$PATH

jobs:
  include:
    - stage: Verify
      script:
        - make install.tools
        - make .gitvalidation
        - make verify
      go: 1.8.x
    - script:
        - make install.tools
        - make .gitvalidation
        - make verify
      go: tip
    - stage: Build and Test
      script:
        - make install.deps
        - make test
        - make binaries
        - make test-cri
      go: 1.8.x
    - script:
        - make install.deps
        - make test
        - make binaries
        - make test-cri
      go: tip

after_script:
    # Abuse travis to preserve the log.
    # TODO(random-liu): Use prow for integration test.
    - cat /tmp/cri-containerd.log
    - cat /tmp/containerd.log
