language: go

sudo: required

services:
    - docker

before_install:
    # libseccomp in trusty is not new enough, need backports version.
    - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' > /etc/apt/sources.list.d/backports.list"
    - sudo apt-get update

install:
    - sudo apt-get install btrfs-tools
    - sudo apt-get install libseccomp2/trusty-backports
    - sudo apt-get install libseccomp-dev/trusty-backports
    - sudo apt-get install libapparmor-dev
    - sudo apt-get install socat
    - docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter

before_script:
    - export PATH=$HOME/gopath/bin:$PATH

jobs:
  include:
    - stage: Build
      script:
        - make install.tools
        - make .gitvalidation
        - make verify
        - make binaries
        - make release
      go: 1.8.x
    - script:
        - make install.tools
        - make .gitvalidation
        - make verify
        - make binaries
        - make release
      go: tip
    - stage: Test
      script:
        - make install.deps
        - make test
        - make test-cri
      after_script:
        # Abuse travis to preserve the log.
        - cat /tmp/test-cri/cri-containerd.log
        - cat /tmp/test-cri/containerd.log
      go: 1.8.x
    - stage: E2E Test
      script:
        - test "${TRAVIS_EVENT_TYPE}" != "cron" && exit 0 || true
        - make install.deps
        - make test-e2e-node
        # TODO(random-liu): Upload log to GCS.
      go: 1.8.x
